[package]
name = "nwschart"
version = "0.1.0"
authors = ["Matt Jones <jonesmr@gmail.com>"]

[[bin]]
name = "nwschart-server"
path = "src/server.rs"

[dependencies]
futures = "*"
getopts = "*"
handlebars = "*"
hyper = "*"
rustc-serialize = "*"
tokio-core = "*"
time = "*"
xmltree = "*"
